from __future__ import annotations

import json
from pathlib import Path
import sys

from pptx import Presentation


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
TESTS_DIR = Path(__file__).resolve().parent
if str(TESTS_DIR) not in sys.path:
    sys.path.insert(0, str(TESTS_DIR))

from scripts.build_source_backed_deck import build_source_backed_deck  # noqa: E402
from scripts.polish_source_backed_deck_language import polish_deck_language  # noqa: E402
from scripts.validate_source_backed_deck_semantics import validate_deck_semantics  # noqa: E402

from test_build_source_backed_deck import _deck_text, _truth_packet  # noqa: E402


def test_polish_then_semantic_gate_passes_builder_output(tmp_path: Path) -> None:
    deck_path = tmp_path / "deck.pptx"
    build_source_backed_deck(
        truth_packet_path=_truth_packet(tmp_path),
        output_path=deck_path,
    )

    polish = polish_deck_language(
        deck_path=deck_path,
        snapshot_date="2026-04-30",
        source_run_id="run-a",
        output_path=tmp_path / "polish.json",
    )
    polished_text = _deck_text(Presentation(str(deck_path)))
    semantics = validate_deck_semantics(
        deck_path=deck_path,
        snapshot_date="2026-04-30",
        source_run_id="run-a",
        output_path=tmp_path / "semantics.json",
    )

    assert polish["status"] == "ok"
    assert polish["summary"]["replacements_applied_count"] > 0
    assert "standard deck production" not in polished_text
    assert "source_json_path" not in polished_text
    assert "Evidence run archived in release packet" in polished_text
    assert semantics["status"] == "ok"
    assert semantics["summary"]["human_style_score"] >= 85
    assert Path(semantics["output_path"]).exists()


def test_semantic_gate_blocks_ai_placeholder_language(tmp_path: Path) -> None:
    deck_path = tmp_path / "ai-placeholder.pptx"
    presentation = Presentation()
    slide = presentation.slides.add_slide(presentation.slide_layouts[6])
    textbox = slide.shapes.add_textbox(0, 0, 6_000_000, 1_000_000)
    textbox.text = "TODO generated by AI"
    presentation.save(deck_path)

    audit = validate_deck_semantics(
        deck_path=deck_path,
        min_score=85,
        output_path=tmp_path / "semantics.json",
    )

    assert audit["status"] == "blocked"
    issues = {finding["issue"] for finding in audit["findings"]}
    assert "forbidden_ai_or_placeholder_language" in issues
    assert "required_business_term_missing" in issues
    assert json.loads(Path(audit["output_path"]).read_text(encoding="utf-8"))["status"] == "blocked"
