#!/usr/bin/env python3
"""Validate that the source-backed deck reads like a human business review."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

from pptx import Presentation


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = ROOT / "output" / "source_backed_deck_semantics"
SCHEMA_VERSION = "monthly_platform.source_backed_deck_semantic_audit.v1"
DEFAULT_MIN_SCORE = 85
MIN_WORDS_PER_SLIDE = 18
REQUIRED_BUSINESS_TERMS = [
    "open ARR",
    "deals",
    "Publish gate",
    "forward fallback",
    "think-cell",
    "Truth Status: OK",
]
FORBIDDEN_RE = re.compile(
    r"\b(TODO|TBD|PLACEHOLDER|LOREM|DUMMY|AI-GENERATED|GENERATED BY AI|AS AN AI|CHATGPT|CLAUDE|CODEX)\b",
    re.IGNORECASE,
)
TECHNICAL_TERMS = [
    "source_artifact",
    "source_json_path",
    "DirectorBundle",
    "schema_version",
    "run_manifest",
    "SOQL",
    "payload",
    "build_",
]


def validate_deck_semantics(
    *,
    deck_path: Path,
    output_path: Path | None = None,
    output_root: Path = DEFAULT_OUTPUT_ROOT,
    snapshot_date: str | None = None,
    source_run_id: str | None = None,
    min_score: int = DEFAULT_MIN_SCORE,
) -> dict[str, Any]:
    deck_path = Path(deck_path)
    findings: list[dict[str, Any]] = []
    resolved_snapshot_date = snapshot_date or "unknown-snapshot"
    resolved_run_id = source_run_id or "unknown-run"

    if not deck_path.exists():
        findings.append(_finding("high", "deck_missing", f"Missing deck: {deck_path}"))
        return _write_result(
            payload=_result_payload(
                deck_path=deck_path,
                snapshot_date=resolved_snapshot_date,
                source_run_id=resolved_run_id,
                findings=findings,
                slide_texts=[],
                min_score=min_score,
            ),
            output_path=output_path,
            output_root=output_root,
        )

    try:
        presentation = Presentation(str(deck_path))
    except Exception as exc:
        findings.append(_finding("high", "deck_load_failed", str(exc)))
        return _write_result(
            payload=_result_payload(
                deck_path=deck_path,
                snapshot_date=resolved_snapshot_date,
                source_run_id=resolved_run_id,
                findings=findings,
                slide_texts=[],
                min_score=min_score,
            ),
            output_path=output_path,
            output_root=output_root,
        )

    slide_texts = [_slide_text(slide) for slide in presentation.slides]
    full_text = "\n".join(slide_texts)

    for match in FORBIDDEN_RE.finditer(full_text):
        findings.append(
            _finding(
                "high",
                "forbidden_ai_or_placeholder_language",
                match.group(0),
            )
        )

    for term in REQUIRED_BUSINESS_TERMS:
        if term.lower() not in full_text.lower():
            findings.append(
                _finding(
                    "high",
                    "required_business_term_missing",
                    f"missing required business term: {term}",
                )
            )

    for slide_index, text in enumerate(slide_texts, start=1):
        word_count = len(re.findall(r"\b\w+\b", text))
        if word_count < MIN_WORDS_PER_SLIDE:
            findings.append(
                _finding(
                    "high",
                    "slide_too_thin_for_business_review",
                    f"slide {slide_index}: {word_count} words",
                    slide=slide_index,
                )
            )

    for term in TECHNICAL_TERMS:
        if re.search(re.escape(term), full_text, flags=re.IGNORECASE):
            findings.append(
                _finding(
                    "medium",
                    "implementation_language_visible",
                    f"visible implementation term: {term}",
                )
            )

    score = _human_style_score(findings)
    if score < min_score:
        findings.append(
            _finding(
                "high",
                "human_style_score_below_minimum",
                f"score={score}; min_score={min_score}",
            )
        )

    return _write_result(
        payload=_result_payload(
            deck_path=deck_path,
            snapshot_date=resolved_snapshot_date,
            source_run_id=resolved_run_id,
            findings=findings,
            slide_texts=slide_texts,
            min_score=min_score,
        ),
        output_path=output_path,
        output_root=output_root,
    )


def _slide_text(slide) -> str:
    texts: list[str] = []
    for shape in slide.shapes:
        if hasattr(shape, "text") and shape.text:
            texts.append(str(shape.text))
        if getattr(shape, "has_table", False):
            for row in shape.table.rows:
                for cell in row.cells:
                    if cell.text:
                        texts.append(str(cell.text))
    return "\n".join(texts)


def _human_style_score(findings: list[dict[str, Any]]) -> int:
    score = 100
    for finding in findings:
        severity = finding.get("severity")
        if severity == "high":
            score -= 40
        elif severity == "medium":
            score -= 8
        else:
            score -= 2
    return max(0, score)


def _result_payload(
    *,
    deck_path: Path,
    snapshot_date: str,
    source_run_id: str,
    findings: list[dict[str, Any]],
    slide_texts: list[str],
    min_score: int,
) -> dict[str, Any]:
    score = _human_style_score(findings)
    high_count = sum(1 for finding in findings if finding["severity"] == "high")
    medium_count = sum(1 for finding in findings if finding["severity"] == "medium")
    return {
        "schema_version": SCHEMA_VERSION,
        "status": "blocked" if high_count else "ok",
        "snapshot_date": snapshot_date,
        "source_run_id": source_run_id,
        "deck_path": str(deck_path),
        "checks": {
            "slide_count": len(slide_texts),
            "business_readiness_checked": deck_path.exists(),
            "required_business_terms": REQUIRED_BUSINESS_TERMS,
            "human_style_score": score,
            "min_score": min_score,
        },
        "summary": {
            "finding_count": len(findings),
            "high_finding_count": high_count,
            "medium_finding_count": medium_count,
            "low_finding_count": sum(
                1 for finding in findings if finding["severity"] == "low"
            ),
            "human_style_score": score,
        },
        "findings": findings,
    }


def _write_result(
    *,
    payload: dict[str, Any],
    output_path: Path | None,
    output_root: Path,
) -> dict[str, Any]:
    if output_path is None:
        output_path = (
            Path(output_root)
            / payload["snapshot_date"]
            / payload["source_run_id"]
            / "source_backed_deck_semantic_audit.json"
        )
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload["output_path"] = str(output_path)
    output_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return payload


def _finding(
    severity: str,
    issue: str,
    evidence: str,
    *,
    slide: int | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "severity": severity,
        "issue": issue,
        "evidence": evidence,
    }
    if slide is not None:
        payload["slide"] = slide
    return payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--deck-path", type=Path, required=True)
    parser.add_argument("--snapshot-date")
    parser.add_argument("--source-run-id")
    parser.add_argument("--min-score", type=int, default=DEFAULT_MIN_SCORE)
    parser.add_argument("--output-path", type=Path)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    payload = validate_deck_semantics(
        deck_path=args.deck_path,
        output_path=args.output_path,
        output_root=args.output_root,
        snapshot_date=args.snapshot_date,
        source_run_id=args.source_run_id,
        min_score=args.min_score,
    )
    print(json.dumps(payload, indent=2))
    return 0 if payload["status"] == "ok" else 1


if __name__ == "__main__":
    raise SystemExit(main())
