#!/usr/bin/env python3
"""Validate the source-backed deck package before monthly publish."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

from pptx import Presentation


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = ROOT / "output" / "source_backed_deck_visuals"
SCHEMA_VERSION = "monthly_platform.source_backed_deck_visual_audit.v1"
DEFAULT_REQUIRED_TITLES = [
    "Monthly Sales Director Operating Review",
    "Publish gate status",
    "Regional open pipeline",
    "Director book view",
    "Quarter display logic",
    "Leadership readout",
]
DEFAULT_REQUIRED_TEXT = [
    "Source-backed",
    "Truth Status",
    "Publish gate",
    "Quarter display logic",
    "think-cell",
]
PLACEHOLDER_RE = re.compile(
    r"\b(TODO|TBD|PLACEHOLDER|LOREM|DUMMY|AI-GENERATED|GENERATED BY AI|SLIDE NUMBER)\b",
    re.IGNORECASE,
)


def validate_deck_visuals(
    *,
    deck_path: Path,
    truth_packet_path: Path | None = None,
    manifest_path: Path | None = None,
    min_slides: int = 6,
    output_path: Path | None = None,
    output_root: Path = DEFAULT_OUTPUT_ROOT,
) -> dict[str, Any]:
    deck_path = Path(deck_path)
    truth_packet = _load_optional_json(truth_packet_path)
    manifest = _load_optional_json(manifest_path)
    findings: list[dict[str, Any]] = []
    slide_texts: list[str] = []
    slide_shape_counts: list[int] = []
    table_count = 0
    chart_count = 0

    if not deck_path.exists():
        findings.append(_finding("high", "deck_missing", f"Missing deck: {deck_path}"))
        return _write_result(
            payload=_result_payload(
                deck_path=deck_path,
                truth_packet_path=truth_packet_path,
                manifest_path=manifest_path,
                findings=findings,
                slide_texts=[],
                slide_shape_counts=[],
                table_count=0,
                chart_count=0,
                truth_packet=truth_packet,
                manifest=manifest,
            ),
            output_path=output_path,
            output_root=output_root,
        )

    try:
        presentation = Presentation(str(deck_path))
    except Exception as exc:
        findings.append(_finding("high", "deck_load_failed", str(exc)))
        return _write_result(
            payload=_result_payload(
                deck_path=deck_path,
                truth_packet_path=truth_packet_path,
                manifest_path=manifest_path,
                findings=findings,
                slide_texts=[],
                slide_shape_counts=[],
                table_count=0,
                chart_count=0,
                truth_packet=truth_packet,
                manifest=manifest,
            ),
            output_path=output_path,
            output_root=output_root,
        )

    if len(presentation.slides) < min_slides:
        findings.append(
            _finding(
                "high",
                "slide_count_below_minimum",
                f"{len(presentation.slides)} slides; expected at least {min_slides}",
            )
        )

    for slide_index, slide in enumerate(presentation.slides, start=1):
        text = _slide_text(slide)
        slide_texts.append(text)
        slide_shape_counts.append(len(slide.shapes))
        if len(text.strip()) < 20:
            findings.append(
                _finding(
                    "high",
                    "blank_or_near_blank_slide",
                    f"slide {slide_index} has too little visible text",
                    slide=slide_index,
                )
            )
        for match in PLACEHOLDER_RE.finditer(text):
            findings.append(
                _finding(
                    "high",
                    "placeholder_text",
                    f"slide {slide_index}: {match.group(0)}",
                    slide=slide_index,
                )
            )
        for shape in slide.shapes:
            if getattr(shape, "has_table", False):
                table_count += 1
            if getattr(shape, "has_chart", False):
                chart_count += 1

    full_text = "\n".join(slide_texts)
    for required in _required_titles(manifest):
        if required not in full_text:
            findings.append(
                _finding("high", "required_title_missing", f"missing title text: {required}")
            )
    for required in _required_text(manifest):
        if required not in full_text:
            findings.append(
                _finding("medium", "required_text_missing", f"missing required text: {required}")
            )
    if table_count < 3:
        findings.append(
            _finding("high", "table_count_below_minimum", f"{table_count} tables; expected at least 3")
        )
    if chart_count < 1:
        findings.append(
            _finding("medium", "chart_missing", "expected at least one native chart object")
        )
    if deck_path.stat().st_size < 25_000:
        findings.append(
            _finding(
                "medium",
                "deck_file_size_suspiciously_small",
                f"{deck_path.stat().st_size} bytes",
            )
        )
    _validate_truth_summary_text(full_text, truth_packet, findings)

    payload = _result_payload(
        deck_path=deck_path,
        truth_packet_path=truth_packet_path,
        manifest_path=manifest_path,
        findings=findings,
        slide_texts=slide_texts,
        slide_shape_counts=slide_shape_counts,
        table_count=table_count,
        chart_count=chart_count,
        truth_packet=truth_packet,
        manifest=manifest,
    )
    return _write_result(payload=payload, output_path=output_path, output_root=output_root)


def _load_optional_json(path: Path | None) -> dict[str, Any] | None:
    if path is None or not Path(path).exists():
        return None
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path}: expected JSON object")
    return payload


def _slide_text(slide) -> str:
    texts: list[str] = []
    for shape in slide.shapes:
        if hasattr(shape, "text") and shape.text:
            texts.append(str(shape.text))
        if getattr(shape, "has_table", False):
            for row in shape.table.rows:
                for cell in row.cells:
                    if cell.text:
                        texts.append(str(cell.text))
        if getattr(shape, "has_chart", False):
            chart = shape.chart
            if chart.chart_title and chart.chart_title.has_text_frame:
                texts.append(chart.chart_title.text_frame.text)
    return "\n".join(texts)


def _required_titles(manifest: dict[str, Any] | None) -> list[str]:
    titles = ((manifest or {}).get("visual_contract") or {}).get("required_titles")
    if isinstance(titles, list) and titles:
        return [str(title) for title in titles]
    return DEFAULT_REQUIRED_TITLES


def _required_text(manifest: dict[str, Any] | None) -> list[str]:
    required = ((manifest or {}).get("visual_contract") or {}).get("required_text")
    if isinstance(required, list) and required:
        return [str(item) for item in required]
    return DEFAULT_REQUIRED_TEXT


def _validate_truth_summary_text(
    full_text: str,
    truth_packet: dict[str, Any] | None,
    findings: list[dict[str, Any]],
) -> None:
    if not truth_packet:
        return
    summary = truth_packet.get("summary") or {}
    required_values = {
        "director_count": str(summary.get("director_count", "")),
        "claim_count": str(summary.get("claim_count", "")),
        "high_blocker_count": str(summary.get("high_blocker_count", "")),
        "tieout_mismatch_count": str(summary.get("tieout_mismatch_count", "")),
    }
    for key, value in required_values.items():
        if value and value not in full_text:
            findings.append(
                _finding(
                    "medium",
                    "truth_summary_value_missing",
                    f"{key}={value} not visible in deck text",
                )
            )
    if truth_packet.get("status") == "ok" and "Truth Status: OK" not in full_text:
        findings.append(
            _finding("medium", "truth_status_not_visible", "Truth Status: OK not visible")
        )


def _result_payload(
    *,
    deck_path: Path,
    truth_packet_path: Path | None,
    manifest_path: Path | None,
    findings: list[dict[str, Any]],
    slide_texts: list[str],
    slide_shape_counts: list[int],
    table_count: int,
    chart_count: int,
    truth_packet: dict[str, Any] | None,
    manifest: dict[str, Any] | None,
) -> dict[str, Any]:
    snapshot_date = str(
        (truth_packet or {}).get("snapshot_date")
        or (manifest or {}).get("snapshot_date")
        or "unknown-snapshot"
    )
    source_run_id = str((manifest or {}).get("source_run_id") or "unknown-run")
    high_count = sum(1 for finding in findings if finding["severity"] == "high")
    medium_count = sum(1 for finding in findings if finding["severity"] == "medium")
    return {
        "schema_version": SCHEMA_VERSION,
        "status": "blocked" if high_count else "ok",
        "snapshot_date": snapshot_date,
        "source_run_id": source_run_id,
        "deck_path": str(deck_path),
        "truth_packet_path": str(truth_packet_path) if truth_packet_path else None,
        "manifest_path": str(manifest_path) if manifest_path else None,
        "checks": {
            "slide_count": len(slide_texts),
            "blank_or_near_blank_slide_count": sum(
                1 for text in slide_texts if len(text.strip()) < 20
            ),
            "table_count": table_count,
            "chart_count": chart_count,
            "file_size_bytes": deck_path.stat().st_size if deck_path.exists() else 0,
            "pptx_package_checked": deck_path.exists(),
            "rendered_png_checked": False,
            "powerpoint_parity_checked": False,
            "slide_shape_counts": slide_shape_counts,
        },
        "summary": {
            "finding_count": len(findings),
            "high_finding_count": high_count,
            "medium_finding_count": medium_count,
            "low_finding_count": sum(
                1 for finding in findings if finding["severity"] == "low"
            ),
        },
        "findings": findings,
    }


def _write_result(
    *,
    payload: dict[str, Any],
    output_path: Path | None,
    output_root: Path,
) -> dict[str, Any]:
    if output_path is None:
        output_path = (
            Path(output_root)
            / payload["snapshot_date"]
            / payload["source_run_id"]
            / "source_backed_deck_visual_audit.json"
        )
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload["output_path"] = str(output_path)
    output_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return payload


def _finding(
    severity: str,
    issue: str,
    evidence: str,
    *,
    slide: int | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "severity": severity,
        "issue": issue,
        "evidence": evidence,
    }
    if slide is not None:
        payload["slide"] = slide
    return payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--deck-path", type=Path, required=True)
    parser.add_argument("--truth-packet", type=Path, default=None)
    parser.add_argument("--manifest-path", type=Path, default=None)
    parser.add_argument("--min-slides", type=int, default=6)
    parser.add_argument("--output-path", type=Path, default=None)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    payload = validate_deck_visuals(
        deck_path=args.deck_path,
        truth_packet_path=args.truth_packet,
        manifest_path=args.manifest_path,
        min_slides=args.min_slides,
        output_path=args.output_path,
        output_root=args.output_root,
    )
    print(json.dumps(payload, indent=2))
    return 0 if payload["status"] == "ok" else 1


if __name__ == "__main__":
    raise SystemExit(main())
